#!/bin/sh

# exit when any command fails
set -e

# check formatting
echo "checking format with rustfmt..."
rustup component add rustfmt # if it's not already installed
cargo fmt --all -- --check

# check for lint
echo "removing lint with clippy..."
rustup component add clippy # if it's not already installed
cargo clippy --all-targets --all-features -- -D warnings

# check documentation coverage whenever --show-coverage is stabilized
# see: https://github.com/rust-lang/rust/issues/58154
# cargo rustdoc -- --show-coverage

# check that the project builds
echo "building..."
cargo build --verbose

# run tests
# echo "testing..."
# cargo test

# install tarpaulin if it's not already installed
# if we try to install it and it already exists, GitHub CI fails with
#   error: binary `cargo-tarpaulin` already exists in destination
if [ "$(cargo install --list | grep -c cargo-tarpaulin)" -eq 0 ]; then
  cargo install cargo-tarpaulin --version=0.27.2
fi

# run tests with coverage
echo "running tests with coverage..."
cargo tarpaulin --fail-under 100 # require 100% coverage