#!/bin/sh

# exit when any command fails
set -e

# check formatting
echo "checking format with rustfmt..."
cargo fmt --all -- --check

# check for lint
echo "removing lint with clippy..."
cargo clippy --all-targets --all-features -- -D warnings

# check that the project builds
echo "building..."
cargo build --verbose

# run tests
echo "testing..."
cargo test