#!/bin/sh

# exit when any command fails
set -e

# check formatting
cargo fmt --all -- --check

# check for lint
cargo clippy --all-targets --all-features -- -D warnings

# check that the project builds
cargo build --verbose

# run tests
cargo test