name: example-action
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    types:
      - opened

env:
  CARGO_TERM_COLOR: always

jobs:
  example-job-name:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --verbose
