name: pull-request

# runs on new / reopened PRs and new commits to existing PRs
# see: https://github.com/orgs/community/discussions/25161#discussioncomment-3246673

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint-build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: .githooks/pre-push
        run: .githooks/pre-push