name: pull-request-workflow
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    types:
      - opened

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint-build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: .githooks/pre-push
        run: .githooks/pre-push