name: pull-request

# runs on new / reopened PRs and new commits to existing PRs
# see: https://github.com/orgs/community/discussions/25161#discussioncomment-3246673

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint-build-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: .githooks/pre-push
        run: .githooks/pre-push
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/coverage/html/*.html # don't upload svg images each time